### ISSUE TITLE
你好，启动项目,sql脚本自动执行,请问是在哪里配置？

### ISSUE THREAD

**Issue by 1367356** [qingwenwei/spring-boot-forum#1]
你好，启动项目,sql脚本自动执行,我现在不想让sql脚本自动执行，请问是在哪里配置？

**Comment by weiqingwen** [comment]
你好，感谢关注。Spring Boot项目运行时，会自动查找并执行src/main/resources目录下的schema.sql和data.sql两个sql脚本。
