### ISSUE TITLE
admin登陆后管理页面打开失败

### ISSUE THREAD

**Issue by SHEN-XM** [qingwenwei/spring-boot-forum#2]

**Comment by weiqingwen** [comment]
你好，能具体描述一下报错信息吗？

**Comment by weiqingwen** [comment]
> _No description provided._

你好，能具体描述一下报错信息吗？

**Comment by SHEN-XM** [comment]
![screen shot 2018-11-02 at 6 10 35 pm](https://user-images.githubusercontent.com/30321653/47909356-a6eb5200-deca-11e8-9512-e4efe8b0b18d.png)

**Comment by SHEN-XM** [comment]
![screen shot 2018-11-02 at 2 57 13 pm](https://user-images.githubusercontent.com/30321653/47909386-bff40300-deca-11e8-8235-331711436abe.png)

**Comment by SHEN-XM** [comment]
另外想问下，这个静态图片路径是怎么玩的，设置路径上传也失败，是不是还要配置什么？能否留联系方式交流，大神代码写的很专业

**Comment by SHEN-XM** [comment]
![screen shot 2018-11-05 at 10 34 59 am](https://user-images.githubusercontent.com/30321653/47974890-8bf52980-e0e6-11e8-8674-9e7f46529895.png)
前端我不会，从报错看，好像是type多了

**Comment by weiqingwen** [comment]
> 另外想问下，这个静态图片路径是怎么玩的，设置路径上传也失败，是不是还要配置什么？能否留联系方式交流，大神代码写的很专业

这段时间比较忙，还没来得及看你的问题，我回头再帮你看看。QQ：85182006

**Comment by weiqingwen** [comment]
去掉第一个type就可以了
